SET AUTOCOMMIT TRUE;

CREATE TABLE config_table (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name VARCHAR(100) NOT NULL
);

INSERT INTO config_table (config_name) VALUES ('proxy_config');
INSERT INTO config_table (config_name) VALUES ('default_config');

SELECT COUNT(*) FROM config_table;